# Generated by Django 5.0 on 2025-09-20 01:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(help_text='The title of the movie the user is petitioning for.', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the petition was created.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
