# Generated by Django 5.0 on 2025-09-20 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_petitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petition',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
